In [1]:
# Dependencies
import pandas as pd
import numpy as np

In [2]:
# Load data
file = '../../uncleaned_data/data_by_artist_w_genres.csv'
df = pd.read_csv(file)
df.head()

,artists,acousticness,danceability,duration_ms,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,popularity,key,mode,count,genres
0,"""Cats"" 1981 Original London Cast",0.598500,0.470100,267072.000000,0.376203,0.010261,0.283050,-14.434300,0.209150,114.128800,0.358320,38.200000,5,1,10,['show tunes']
1,"""Cats"" 1983 Broadway Cast",0.862538,0.441731,287280.000000,0.406808,0.081158,0.315215,-10.690000,0.176212,103.044154,0.268865,31.538462,5,1,26,[]
2,"""Fiddler On The Roof” Motion Picture Chorus",0.856571,0.348286,328920.000000,0.286571,0.024593,0.325786,-15.230714,0.118514,77.375857,0.354857,34.571429,0,1,7,[]
3,"""Fiddler On The Roof” Motion Picture Orchestra",0.884926,0.425074,262890.962963,0.245770,0.073587,0.275481,-15.639370,0.123200,88.667630,0.372030,34.407407,0,1,27,[]
4,"""Joseph And The Amazing Technicolor Dreamcoat""...",0.510714,0.467143,270436.142857,0.488286,0.009400,0.195000,-10.236714,0.098543,122.835857,0.482286,42.000000,5,1,7,[]

In [3]:
# Shape of df
df.shape

(32539, 16)

In [4]:
# Take a look at all the columns and check if there's any NaN in the df
df.isna().any()

artists             False
acousticness        False
danceability        False
duration_ms         False
energy              False
instrumentalness    False
liveness            False
loudness            False
speechiness         False
tempo               False
valence             False
popularity          False
key                 False
mode                False
count               False
genres              False
dtype: bool

In [5]:
# Doesn't look like there's any NaN
# Check data types of each column
df.dtypes

artists              object
acousticness        float64
danceability        float64
duration_ms         float64
energy              float64
instrumentalness    float64
liveness            float64
loudness            float64
speechiness         float64
tempo               float64
valence             float64
popularity          float64
key                   int64
mode                  int64
count                 int64
genres               object
dtype: object

##### Since the "genres" column consists of values of lists, an empty list could potentially be regarded as non-NaN values, thus, we will check if there's indeed any missing artist names in this dataset.

In [6]:
len(df.loc[df['genres'] == '[]'])

13563

Looks like there are more than 1/3 of rows from the datasets do not have a genre labeled. Let's take a look at who these artists are to get an idea if we would like to remove these.

In [7]:
df.loc[df['genres'] == '[]'].head(20)

,artists,acousticness,danceability,duration_ms,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,popularity,key,mode,count,genres
1,"""Cats"" 1983 Broadway Cast",0.862538,0.441731,287280.000000,0.406808,0.081158,0.315215,-10.690000,0.176212,103.044154,0.268865,31.538462,5,1,26,[]
2,"""Fiddler On The Roof” Motion Picture Chorus",0.856571,0.348286,328920.000000,0.286571,0.024593,0.325786,-15.230714,0.118514,77.375857,0.354857,34.571429,0,1,7,[]
3,"""Fiddler On The Roof” Motion Picture Orchestra",0.884926,0.425074,262890.962963,0.245770,0.073587,0.275481,-15.639370,0.123200,88.667630,0.372030,34.407407,0,1,27,[]
4,"""Joseph And The Amazing Technicolor Dreamcoat""...",0.510714,0.467143,270436.142857,0.488286,0.009400,0.195000,-10.236714,0.098543,122.835857,0.482286,42.000000,5,1,7,[]
5,"""Joseph And The Amazing Technicolor Dreamcoat""...",0.591167,0.484333,218504.500000,0.300608,0.007042,0.176067,-18.579500,0.104958,122.517833,0.424500,33.166667,9,1,24,[]
6,"""Mama"" Helen Teagarden",0.725000,0.637000,135533.000000,0.512000,0.186000,0.426000,-20.615000,0.210000,134.819000,0.885000,0.000000,8,1,2,[]
7,"""Test for Victor Young""",0.927000,0.734000,175693.000000,0.474000,0.076200,0.737000,-10.544000,0.256000,132.788000,0.902000,3.000000,10,1,2,[]
9,$0dg0d,0.110000,0.732000,160171.000000,0.822000,0.000009,0.154000,-5.387000,0.155000,141.948000,0.740000,0.000000,7,0,2,[]
12,$tar$eed,0.037500,0.923000,130375.000000,0.172000,0.020200,0.082700,-15.646000,0.385000,100.046000,0.176000,0.000000,10,0,4,[]
18,(Con La Participación de Marc Anthony),0.538000,0.731000,361440.000000,0.794000,0.000024,0.073600,-4.182000,0.040800,88.003000,0.873000,42.000000,5,1,2,[]
24,+44,0.000367,0.416000,192787.000000,0.967000,0.000000,0.063200,-2.289000,0.109000,171.032000,0.431000,53.000000,9,0,2,[]
25,-Sd-,0.010600,0.880000,451765.000000,0.494000,0.472000,0.115000,-7.633000,0.183000,136.031000,0.261000,0.000000,9,0,4,[]
28,//Tense//,0.000047,0.704000,326632.000000,0.844000,0.442000,0.266000,-9.378000,0.030800,123.011000,0.656000,1.000000,5,1,2,[]
35,100 First Songs' Participants,0.682000,0.676000,53000.000000,0.360000,0.000006,0.062800,-15.708000,0.281000,132.450000,0.593000,34.000000,0,1,2,[]
38,1011 - TEN-ELEVEN,0.740000,0.668000,252027.000000,0.436000,0.000000,0.092300,-7.040000,0.031500,128.135000,0.316000,18.000000,11,1,2,[]
42,12 Inches A Slave,0.001520,0.800000,270350.000000,0.837000,0.911000,0.072900,-8.938000,0.061100,127.987000,0.895000,0.000000,10,1,2,[]
46,1422,0.506000,0.682000,59520.000000,0.872000,0.290000,0.187000,-5.947000,0.060900,117.606000,0.794000,6.000000,7,1,2,[]
48,1776 Ensemble,0.891500,0.589500,193206.500000,0.402500,0.000000,0.472500,-11.348500,0.172000,97.403500,0.594000,21.500000,0,1,2,[]
49,1776 Orchestra,0.080000,0.739000,113493.000000,0.518000,0.865000,0.091700,-15.621000,0.097900,120.939000,0.222000,18.000000,11,1,1,[]
52,1920Johnny,0.508111,0.750778,198440.666667,0.385222,0.000012,0.125967,-10.369444,0.184000,123.955333,0.316611,0.111111,10,0,9,[]

From the artist names it looks like many of could be relatively more niche "artists". Let's also check if there are artists with many songs that do not have a labeled genre.

In [8]:
df.sort_values('count', ascending=False).head()

,artists,acousticness,danceability,duration_ms,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,popularity,key,mode,count,genres
9761,Francisco Canaro,0.984488,0.658213,176800.691098,0.286427,0.542779,0.198878,-12.114052,0.110551,123.000891,0.742906,0.049701,2,1,3179,"['tango', 'vintage tango']"
27354,Tadeusz Dolega Mostowicz,0.451377,0.680885,132738.188915,0.222287,0.000010,0.204249,-23.232556,0.955717,105.357162,0.565923,0.000000,1,1,2562,[]
32374,Эрнест Хемингуэй,0.351897,0.696763,116385.067234,0.188663,0.000028,0.372711,-18.236630,0.926439,111.517753,0.587283,0.035745,11,1,2350,[]
32373,Эрих Мария Ремарк,0.298241,0.693759,121067.432203,0.200422,0.000231,0.196048,-19.254032,0.921459,110.731847,0.536123,0.000942,0,1,2124,[]
9832,Frank Sinatra,0.743164,0.383003,189404.126132,0.233773,0.019481,0.233630,-14.441736,0.049390,109.540857,0.363877,28.363763,5,1,1435,"['adult standards', 'easy listening', 'lounge']"

It appears there are three non-English artists in the top 5 artists with the most songs, that, do not have genre labels. Considering these rows are a big part of the dataset and they also appear in top song counts, we will decide not to remove them for now. We can remove them any time throughout the project on a case by case basis.

As a result, we feel comfortable enough with the existing dataset so we decided to use as is.

In [9]:
# Export file as a CSV, without index, but with header
df.to_csv("../../cleaned_data/cleaned_data_by_artist.csv", index=False, header=True)